name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_deps_vulkan
      run: wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.170-focal.list https://packages.lunarg.com/vulkan/1.2.170/lunarg-vulkan-1.2.170-focal.list && sudo apt update && sudo apt install vulkan-sdk
    - name: install_deps_glfw
      run: sudo apt-get install libglfw3-dev
    - name: install_deps_glm
      run: sudo apt-get install libglm-dev
    - name: update gcc
      run: sudo apt-get install gcc-10 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 700 --slave /usr/bin/g++ g++ /usr/bin/g++-9 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 800 --slave /usr/bin/g++ g++ /usr/bin/g++-10
    - name: submodules
      run: git submodule update --init --recursive
    - name: configure
      run: cmake . -D TGA_BUILD_EXAMPLES=1
    - name: make 
      run: make -j${nproc}
    - uses: actions/upload-artifact@v1
      with:
        name: heightmapDemo
        path: examples/heightmapDemo/heightmapDemo
    - uses: actions/upload-artifact@v1
      with:
        name: objViewer
        path: examples/objViewer/objViewer
    - uses: actions/upload-artifact@v1
      with:
        name: particleDemo
        path: examples/particleDemo/particleDemo
