name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_deps_vulkan
      run: wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.131-bionic.list http://packages.lunarg.com/vulkan/1.2.131/lunarg-vulkan-1.2.131-bionic.list && sudo apt update && sudo apt install vulkan-sdk
    - name: install_deps_glfw
      run: sudo apt-get install libglfw3-dev
    - name: install_deps_glm
      run: sudo apt-get install libglm-dev
    - name: configure
      run: cmake .
    - name: make
      run: make
    - uses: actions/upload-artifact@v1
      with:
        name: sandbox
        path: sandbox/sandbox
    - uses: actions/upload-artifact@v1
      with:
        name: terrainViewer
        path: sandbox/terrainViewer
